version: '3'
services:
  bridge:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: senither/hypixel-discord-chat-bridge
    environment:
      SERVER_HOST: mc.hypixel.net
      SERVER_PORT: 25565
      MINECRAFT_USERNAME: yourUsername
      MINECRAFT_PASSWORD: yourPassword
      MINECRAFT_ACCOUNT_TYPE: mojang
      DISCORD_TOKEN: yourDiscordToken
      DISCORD_CHANNEL: discordChannelId
      DISCORD_COMMAND_ROLE: discordCommandRoleId
      DISCORD_OWNER_ID: discordOwnerId
